# Generated by Django 3.2.6 on 2024-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_id', models.CharField(max_length=255)),
                ('impression_city', models.CharField(max_length=255)),
                ('posting_user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('viewer_email', models.EmailField(max_length=255)),
                ('impression_country', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('device', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
