# Generated by Django 3.2.6 on 2024-07-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_jsoncsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
